### ISSUE TITLE
Problems with SSH Authentication Within API Calls

### ISSUE THREAD

**Issue by isaac-darling** [ChameleonCloud/python-chi#13]
# Mistake in Storage of id_rsa File Compared to Expected

I believe I found a mistake in the way the file `~/work/.ssh/id_rsa` is stored. The python-chi API seems to want a file in that location, with that name, with the `.pub` extension.
The file that is there is the private key, so the public key must be generated.

![id_rsa_file_err](https://user-images.githubusercontent.com/61167692/123999067-b8e16380-d997-11eb-85a3-8b0f13d1c48d.png)

The file was found after the following operation.

#### ssh-keygen -y -f id_rsa > id_rsa.pub && ls

Additionally, the default key is of the form: -----BEGIN OPENSSH PRIVATE KEY-----
Where the API requires a key in the form: -----BEGIN RSA PRIVATE KEY-----
The command to fix this is below.

#### sudo ssh-keygen -m pem -f id_rsa

**Comment by super-cooper** [comment]
Hi Isaac!

I believe the code is behaving as expected. SSH authentication is based on the concept of _asymmetric_ or _public/private key_ cryptography. The way this works is by generating a pair of cryptographic keys: one which is fine to share with the public (your public key) and one which is **very strictly** a secret (your private key). 

Essentially,  you can think of your private key as a password that you should never under any circumstances divulge to anybody. You authenticate to a server with it, and this is secure because you make a [cryptographic key exchange](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange) to derive the same shared secret used for authentication without _ever_ having to send your private key across the network! This is all based on some pretty complicated math, but all you need to know is that it is deterministic and secure if done properly (which SSH does). If you want to read more specifically about how SSH exchanges keys, I found a neat [article](https://goteleport.com/blog/ssh-handshake-explained/) on the SSH key exchange (KEX) 

That being said, `python-chi`, just like any other SSH client, requires both your private key (`id_rsa`) and your public key (`id_rsa.pub`) to authenticate. If you have been sending your private key to any remote servers, I would recommend invalidating those authentication mechanisms and creating a new keypair from scratch. (for example, if you have used your private key as an identity on any servers for SSH, you should delete your private key from that server's `known_hosts` using `ssh-add -d`. Also, if you've uploaded your private key to Chameleon,  you should dele it there, and anywhere else you may have uploaded it. 

If you want to be able to SSH into a server using your keys instead of a password (I do this for every server I regularly SSH into), you can do the following steps:

```shell
# generate a new keypair
ssh-keygen  
# the next command authenticates your public key to the remote host
# you will have to sign in with your password (this is how the server knows that your public key is authentic)
ssh-copy-id <your-remote-username>@<remote-host>  
# test by sshing into the server (you should be able to do this now without entering a password :D)
ssh <your-remote-username>@<remote-host>
```

If I've misunderstood your report, or you have any other questions or comments, feel free to re-open this issue :)

**Comment by isaac-darling** [comment]
I wrote this issue as more of a notice that the default behavior of a fresh Jupyter account (I guess it's an account?) cannot successfully validate to a Chameleon node when using the Python library. Jonathan recently attempted to and ran into the same I did (SSHException: Invalid key), so I am assuming the "issue" is present on all fresh accounts. If that behavior is intended, then of course this is not a problem. I just assumed that it was supposed to work out-of-the-box without running the commands like I did that solved the exception. Ultimately, because I do not know the intended behavior, I will leave the issue closed--but I think it can also serve as a resource if other people run into that problem.

**Comment by super-cooper** [comment]
Ok, I just want to make sure I am understanding the issue correctly. I have some questions:

1. Were you authenticating from your local machine, or from a remote one?
2. How were the keys generated? Did you do it yourself? Were they already on your machine? 
3. Did you pass in a keypath or was it derived automatically?

Sorry for all the questions! I started working on Chameleon recently and don't quite know everything about the internals, but based on my knowledge of Linux and security, something seems strange here.

**Comment by isaac-darling** [comment]
1. I was authenticating from JupyterLab, so it was their server
2. There was one key on the machine by default, an OpenSSH private key
3. The path to the key was specified inside the API

And to be clear about the problems:
1. I had to make the public key from the private key
2. I had to convert the OpenSSH private key into an RSA private key

**Comment by super-cooper** [comment]
Ah, understood. I did misunderstand the issue. Thank you for clarifying :)

I'm going to look into why this was the case.

**Comment by diurnalist** [comment]
@super-cooper my student also encountered an issue here. I think the issue might be that paramiko is uncertain how to parse the private key file.

full stack that my student got:
```
---------------------------------------------------------------------------
SSHException                              Traceback (most recent call last)
<ipython-input-21-6371ede109d2> in <module>
      6 chi.server.wait_for_tcp(host, port=22)
      7 
----> 8 remote.run("mkdir teste_pasta")

<decorator-gen-3> in run(self, command, **kwargs)

/opt/conda/lib/python3.8/site-packages/fabric/connection.py in opens(method, self, *args, **kwargs)
     27 @decorator
     28 def opens(method, self, *args, **kwargs):
---> 29     self.open()
     30     return method(self, *args, **kwargs)
     31 

/opt/conda/lib/python3.8/site-packages/fabric/connection.py in open(self)
    634             del kwargs["key_filename"]
    635         # Actually connect!
--> 636         self.client.connect(**kwargs)
    637         self.transport = self.client.get_transport()
    638 

/opt/conda/lib/python3.8/site-packages/paramiko/client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, gss_trust_dns, passphrase, disabled_algorithms)
    433             key_filenames = key_filename
    434 
--> 435         self._auth(
    436             username,
    437             password,

/opt/conda/lib/python3.8/site-packages/paramiko/client.py in _auth(self, username, password, pkey, key_filenames, allow_agent, look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host, passphrase)
    762         # if we got an auth-failed exception earlier, re-raise it
    763         if saved_exception is not None:
--> 764             raise saved_exception
    765         raise SSHException("No authentication methods available")
    766 

/opt/conda/lib/python3.8/site-packages/paramiko/client.py in _auth(self, username, password, pkey, key_filenames, allow_agent, look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host, passphrase)
    674                 for pkey_class in (RSAKey, DSSKey, ECDSAKey, Ed25519Key):
    675                     try:
--> 676                         key = self._key_from_filepath(
    677                             key_filename, pkey_class, passphrase
    678                         )

/opt/conda/lib/python3.8/site-packages/paramiko/client.py in _key_from_filepath(self, filename, klass, password)
    584             cert_path = filename + cert_suffix
    585         # Blindly try the key path; if no private key, nothing will work.
--> 586         key = klass.from_private_key_file(key_path, password)
    587         # TODO: change this to 'Loading' instead of 'Trying' sometime; probably
    588         # when #387 is released, since this is a critical log message users are

/opt/conda/lib/python3.8/site-packages/paramiko/pkey.py in from_private_key_file(cls, filename, password)
    204         :raises: `.SSHException` -- if the key file is invalid
    205         """
--> 206         key = cls(filename=filename, password=password)
    207         return key
    208 

/opt/conda/lib/python3.8/site-packages/paramiko/ed25519key.py in __init__(self, msg, data, filename, password, file_obj)
     81 
     82         if filename or file_obj:
---> 83             signing_key = self._parse_signing_key_data(data, password)
     84 
     85         if signing_key is None and verifying_key is None:

/opt/conda/lib/python3.8/site-packages/paramiko/ed25519key.py in _parse_signing_key_data(self, data, password)
    130             pubkey = Message(message.get_binary())
    131             if pubkey.get_text() != "ssh-ed25519":
--> 132                 raise SSHException("Invalid key")
    133             public_keys.append(pubkey.get_binary())
    134 

SSHException: Invalid key
```

The exception is a bit of a red herring, as it just raises the last one it saved. It tries to process the private key as one of 4 different formats, and it's failing on each one. It should succeed on the first format, which is RSAKey. @isaac-darling 's comment that changing the type to PEM is interesting; maybe the way we're generating keypairs is not compatible w/ paramiko at the moment, or we need to pass it another flag or something to tell it what type of key it is?
